src/risks/urls.py
# -*- coding: utf-8 -*-
"""ecoquartier URL Configuration
"""
from django.conf.urls import url, include
from django.contrib import admin

from surveys.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
]

admin.site.site_header = u"Jeu Coné les Risks"

src/surveys/models.py
from __future__ import unicode_literals

from django.db import models


class Survey(models.Model):
    lat = models.FloatField()
    lng = models.FloatField()
    innodation = models.BooleanField()
    argile = models.BooleanField()
    mouvement_terrain = models.BooleanField()
    cavite = models.BooleanField()
    seisme = models.BooleanField()
    sites_pollues = models.BooleanField()
    installations_classees = models.BooleanField()
    canalisation = models.BooleanField()
    nucleair = models.BooleanField()

src/surveys/forms.py
from django.forms import ModelForm

from .models import Survey


class SurveyForm(ModelForm):

    class Meta:
        model = Survey
        fields = '__all__'

src/surveys/views.py
# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from scrapy.selector import Selector

import random

from django.shortcuts import render

from .forms import SurveyForm

def scrap(lat, lng):

    url = 'http://www.georisques.gouv.fr/ma_maison_mes_risques/rapport?lon=%s&lat=%s' % (lng, lat)
    print url
    # browser = webdriver.PhantomJS()
    # browser.get(url)

    # html = browser.page_source
    html = False
    # selector = Selector(text=html)

    data = [
        {'fieldset':u'Innondations',
         'fields':[
            {'label':u'Localisation exposée à une remontée de nappe dans les sédiments', 'xpath':'//*[@id="alea-INN"]/ul[2]/li[1]/text()'},
            {'label':u'Localisation exposée à une remontée de nappe dans le socle', 'xpath':'//*[@id="alea-INN"]/ul[3]/li/text()'},
            {'label':u'Type d\'exposition', 'xpath':'//*[@id="alea-INN"]/ul[3]/li[2]/text()'},
        ]},
        {'fieldset':u'Retrait-gonflements des argiles',
         'fields':[
            {'label':u'Localisation exposée aux retrait-gonflements des argiles', 'xpath':'//*[@id="alea-RETRAIT"]/ul[2]/li[1]/text()'},
            {'label':u'Type d\'exposition', 'xpath':'//*[@id="alea-RETRAIT"]/ul[2]/li[2]/text()'},
        ]},
        {'fieldset':u'Mouvements de terrain',
         'fields':[
            {'label':u'Mouvements de terrain recensés dans un rayon de 200m', 'xpath':'//*[@id="alea-MVMT"]/ul[2]/li/text()'},
        ]},
        {'fieldset':u'Cavités souterraines',
         'fields':[
            {'label':u'Cavités recensées dans un rayon de 200m', 'xpath':'//*[@id="alea-CAV"]/ul[2]/li/text()'},
        ]},
        {'fieldset':u'Séismes',
         'fields':[
            {'label':u'Localisation exposée aux séismes', 'xpath':'//*[@id="alea-SEISM"]/ul[2]/li[1]/text()'},
            {'label':u'Type d\'exposition', 'xpath':'//*[@id="alea-SEISM"]/ul[2]/li[2]/text()'},
        ]},
        {'fieldset':u'Sites et sols industriels',
         'fields':[
            {'label':u'Sites pollués dans un rayon de 200m', 'xpath':'//*[@id="alea-POL"]/ul[1]/li/text()'},
            {'label':u'Ancien site industriel et activité de service non localisé sur la commune', 'xpath':'//*[@id="alea-POL"]/ul[2]/li[2]/span/text()'},
            {'label':u'Ancien site industriel et activité de service dans un rayon de 200 m', 'xpath':'//*[@id="alea-POL"]/ul[2]/li[3]/span/text()'},
        ]},
        {'fieldset':u'Installations classées',
         'fields':[
            {'label':u'Votre installation est concernée par des installations classées', 'xpath':'//*[@id="alea-INST"]/ul[2]/li[1]/text()'},
            {'label':u'Votre installation est impactée par des installations classées', 'xpath':'//*[@id="alea-INST"]/ul[2]/li[2]/text()'},
            {'label':u'Votre installation est concernée par des installations rejetant des polluants dans un rayon de 5 km', 'xpath':'//*[@id="alea-INST"]/ul[3]/li/text()'},
        ]},
        {'fieldset':u'Canalisations de matières dangereuses',
         'fields':[
            {'label':u'Canalisations de matières dangereuses dans un rayon de 100m', 'xpath':'//*[@id="alea-CAN"]/ul/li/text()'},
        ]},
        {'fieldset':u'Installations nucléaires',
         'fields':[
            {'label':u'Installations nucléaires dans un rayon de 10km', 'xpath':'//*[@id="alea-NUC"]/ul/li[1]/text()'},
            {'label':u'Centrales nucléaires dans un rayon de 20km', 'xpath':'//*[@id="alea-NUC"]/ul/li[2]/text()'},
        ]},
    ]

    for d in data:
        for f in d['fields']:
            # try:
            #     f['value'] = selector.xpath(f['xpath']).extract()
            # except:
            f['value'] = random.choice([True, False])

    results = []
    for d in data:
        vals = [f['value'] for f in d['fields']]
        if any(vals):
            results.append(True)
        else:
            results.append(False)

    return results, data, html


def home(request):
    if request.method == "POST":
        form = SurveyForm(request.POST)
        if form.is_valid():
            instance = form.save()
            lat = instance.lat
            lng = instance.lng
            results, data, html = scrap(lat, lng)
            print results
            return render(request, 'result.html', {
                'form': form,
                'instance': instance,
                'results': results,
                'html': html
            })
    form = SurveyForm()
    return render(request, 'home.html', {
        'form': form
    })

src/risks/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">

    {% block head %}
    {% endblock %}
  </head>
  <body>
  <div class="container">
    <nav class="navbar navbar-light bg-faded">
      <a class="navbar-brand" href="{% url 'home' %}">Jeu Coné lé Risk</a>
    </nav>

    {% block body %}
    {% endblock %}

  </div>
  <!-- jQuery first, then Tether, then Bootstrap JS. -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
  {% block endbody %}
  {% endblock %}
  </body>
</html>

src/risks/templates/home.html
{% extends 'base.html' %}

{% block head %}
<style type="text/css">
  .form {
    display: none;
  }
</style>

<script type="text/javascript">
  var options = {
    enableHighAccuracy: true,
    timeout: 5000,
    maximumAge: 0
  };

  function success(pos) {
    var crd = pos.coords;
    // console.log('Your current position is:');
    // console.log('Latitude : ' + crd.latitude);
    // console.log('Longitude: ' + crd.longitude);
    // console.log('More or less ' + crd.accuracy + ' meters.');
    $('#id_lat').val(crd.latitude)
    $('#id_lng').val(crd.longitude)
    $('.form').css('display', 'block');
    $('#load').css('display', 'none');
  };

  function error(err) {
    // console.warn('ERROR(' + err.code + '): ' + err.message);
    $('#load').css('display', 'none');
    $('#error').css('display', 'block');
    $('.form').css('display', 'none');
  };

  navigator.geolocation.getCurrentPosition(success, error, options);
</script>
{% endblock %}

{% block body %}
<br>

<div class="card card-inverse card-primary" id="load">
  <div class="card-block">
    <p class="card-blockquote">
    Chargement des données de localisation GPS
    </p>
  </div>
</div>

<div class="card card-inverse card-danger" id="error">
  <div class="card-block">
    <p class="card-blockquote">
      Erreur de Chargement des données de localisation ... <a href="{% url 'home' %}" class="card-link">rechargez la page</a>.
    </p>
  </div>
</div>

<form action="{% url 'home' %}" method="POST">

{% csrf_token %}

<div style="display: none">
{{ form.lat }}
  {{ form.lng }}
</div>

<div class="form">

<h5>A quels risques pensez-vous être exposé à votre localisation actuellement ?</h5>
<hr>

  <div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.innodation }}
    <span class="custom-control-description">Risques d'innondation ?</span>
  </label>
  </div>

<div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.argile }}
    <span class="custom-control-description">Risques de retrait ou gonflements des sols ?</span>
  </label>
  </div>

<div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.mouvement_terrain }}
    <span class="custom-control-description">Risques de mouvements de terrain ?</span>
  </label>
  </div>

<div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.cavite }}
    <span class="custom-control-description">Risques d'affaisements ou d'effondrements ?</span>
  </label>
  </div>

<div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.seisme }}
    <span class="custom-control-description">Risques de séismes ?</span>
  </label>
  </div>

<div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.sites_pollues }}
    <span class="custom-control-description">Sites pollués situés à proximité ?</span>
  </label>
  </div>

<div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.installations_classees }}
    <span class="custom-control-description">Risques industriels à proximité ?</span>
  </label>
  </div>

<div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.canalisation }}
    <span class="custom-control-description">Canalisations de matières dangereuses à proximité ?</span>
  </label>
  </div>

<div class="form-group">
  <label class="custom-control custom-checkbox">
    {{ form.nucleair }}
    <span class="custom-control-description">Risque nucléaire (installation nucléaire ou centrale nucléaire dans un rayon de 20km) ?</span>
  </label>
  </div>

<button class="btn btn-primary btn-block" type='submit'>Valider vos réponses</button>

</div>

</form>

{% endblock %}

{% block endbody %}
<script type="text/javascript">
  $( document ).ready(function() {
    $('#error').css('display', 'none');
  })
</script>
{% endblock %}

src/risks/templates/result.html
{% extends 'base.html' %}

{% block body %}

<br>
<h5>Résultats</h5>
<hr>

{% if instance.innodation == results.0 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Risques d'innondation : {% if instance.innodation %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Risques d'innondation : {% if results.0 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}

{% if instance.argile == results.1 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Risques de retrait ou gonflements des sols : {% if instance.innodation %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Risques de retrait ou gonflements des sols : {% if results.1 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}


{% if instance.mouvement_terrain == results.2 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Risques de mouvements de terrain : {% if instance.mouvement_terrain %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Risques de mouvements de terrain : {% if results.2 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}


{% if instance.cavite == results.3 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Risques d'affaisements ou d'effondrements  : {% if instance.mouvement_terrain %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Risques d'affaisements ou d'effondrements  : {% if results.3 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}

{% if instance.seisme == results.4 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Risques de séismes : {% if instance.mouvement_terrain %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Risques de séismes : {% if results.4 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}

{% if instance.sites_pollues == results.5 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Sites pollués situés à proximité : {% if instance.mouvement_terrain %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Sites pollués situés à proximité : {% if results.5 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}

{% if instance.installations_classees == results.6 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Risques industriels à proximité : {% if instance.mouvement_terrain %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Risques industriels à proximité : {% if results.6 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}

{% if instance.canalisation == results.7 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Canalisations de matières dangereuses à proximité : {% if instance.mouvement_terrain %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Canalisations de matières dangereuses à proximité : {% if results.7 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}

{% if instance.nucleair == results.8 %}
<div class="card card-inverse card-success">
<div class="card-block">
	Risque nucléaire (installation nucléaire ou centrale nucléaire dans un rayon de 20km)  : {% if instance.mouvement_terrain %}Oui{% else %}Non{% endif %}
</div>
</div>
{% else %}
<div class="card card-inverse card-danger">
<div class="card-block">
	Risque nucléaire (installation nucléaire ou centrale nucléaire dans un rayon de 20km)  : {% if results.8 %}Si{% else %}Non{% endif %}
</div>
</div>
{% endif %}

{% endblock %}